#!/usr/bin/env python3
"""Generate deterministic test vectors for the sobel_top testbench.

Writes tb/tb_vectors.svh (consumed by tb/tb_sobel.sv via `include) and
reports/vector-manifest.json (evidence for the report). The expected outputs
come from the independent reference model ref/sobel_ref.py.

Coverage intent:
  case 0: minimum size 3x3, mid threshold
  case 1: 4x4, threshold 0 (every interior magnitude qualifies)
  case 2: 8x8, threshold 255 (only very strong edges)
  case 3: 16x16, random, mid threshold
  case 4: 32x24, smooth gradient + noise
  case 5: maximum width 128, height 8
  case 6: width 3, height 16384 (exercises the 16-bit row counter)
Frames run back-to-back with different configs, proving per-frame
reconfiguration; the testbench additionally randomizes input stalls.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

from sobel_ref import sobel_ref

ROOT = Path(__file__).resolve().parent.parent
TB_DIR = ROOT / "tb"
REPORT_DIR = ROOT / "reports"


def make_pixels(rng: random.Random, w: int, h: int, kind: str) -> list[int]:
    n = w * h
    if kind == "random":
        return [rng.randrange(256) for _ in range(n)]
    if kind == "gradient":
        return [((r * 7 + c * 3 + rng.randrange(8)) % 256) for r in range(h) for c in range(w)]
    if kind == "edges":
        # vertical/horizontal step edges plus noise
        out = []
        for r in range(h):
            for c in range(w):
                v = 200 if c >= w // 2 else 30
                if r >= h // 2:
                    v = 255 - v
                out.append(max(0, min(255, v + rng.randrange(-5, 6))))
        return out
    if kind == "sparse":
        out = [0] * n
        for _ in range(max(1, n // 16)):
            out[rng.randrange(n)] = 255
        return out
    raise ValueError(kind)


def main() -> None:
    rng = random.Random(42)
    cases = [
        dict(w=3, h=3, thr=128, kind="edges"),
        dict(w=4, h=4, thr=0, kind="random"),
        dict(w=8, h=8, thr=255, kind="random"),
        dict(w=16, h=16, thr=100, kind="random"),
        dict(w=32, h=24, thr=64, kind="gradient"),
        dict(w=128, h=8, thr=200, kind="random"),
        dict(w=3, h=16384, thr=90, kind="random"),
    ]

    all_in: list[int] = []
    all_exp: list[int] = []
    manifest = []
    for idx, case in enumerate(cases):
        pix = make_pixels(rng, case["w"], case["h"], case["kind"])
        exp = sobel_ref(case["w"], case["h"], case["thr"], pix)
        manifest.append(
            dict(
                case=idx,
                width=case["w"],
                height=case["h"],
                threshold=case["thr"],
                kind=case["kind"],
                in_offset=len(all_in),
                pixels=len(pix),
            )
        )
        all_in.extend(pix)
        all_exp.extend(exp)

    def fmt_array(name: str, values: list[int], per_line: int = 16) -> str:
        lines = [f"localparam logic [7:0] {name} [0:{len(values) - 1}] = '{{"]
        for i in range(0, len(values), per_line):
            chunk = ", ".join(f"8'h{v:02X}" for v in values[i : i + per_line])
            lines.append("    " + chunk + ("," if i + per_line < len(values) else ""))
        lines.append("};")
        return "\n".join(lines)

    n = len(cases)
    parts = [
        "// Auto-generated by ref/gen_vectors.py. Do not edit by hand.",
        f"localparam int N_CASES = {n};",
        "localparam int case_w [0:N_CASES-1] = '{" + ", ".join(str(c["w"]) for c in cases) + "};",
        "localparam int case_h [0:N_CASES-1] = '{" + ", ".join(str(c["h"]) for c in cases) + "};",
        "localparam int case_thr [0:N_CASES-1] = '{" + ", ".join(str(c["thr"]) for c in cases) + "};",
        "localparam int case_off [0:N_CASES-1] = '{" + ", ".join(str(m["in_offset"]) for m in manifest) + "};",
        "localparam int case_len [0:N_CASES-1] = '{" + ", ".join(str(m["pixels"]) for m in manifest) + "};",
        fmt_array("stim_in", all_in),
        fmt_array("exp_out", all_exp),
    ]
    TB_DIR.mkdir(exist_ok=True)
    (TB_DIR / "tb_vectors.svh").write_text("\n".join(parts) + "\n")

    REPORT_DIR.mkdir(exist_ok=True)
    (REPORT_DIR / "vector-manifest.json").write_text(
        json.dumps(
            dict(
                generator="ref/gen_vectors.py",
                seed=42,
                reference_model="ref/sobel_ref.py",
                total_input_pixels=len(all_in),
                cases=manifest,
            ),
            indent=2,
        )
        + "\n"
    )
    print(f"generated {n} cases, {len(all_in)} pixels")


if __name__ == "__main__":
    main()
