const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {validatePromptImages, imageContent} = require('../src/image-input.cjs');
const {KimiSession} = require('../src/index.cjs');
const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQkAAAAASUVORK5CYII=';
const image = {id: 'image-1', name: 'Screenshot.png', dataUrl: `data:image/png;base64,${png}`};
test('inline images validate bytes and dimensions; paths, URLs, SVG, duplicates and limits are rejected', () => {
  const checked = validatePromptImages([image]);
  assert.equal(checked[0].width, 1);
  assert.equal(checked[0].height, 1);
  assert.equal(checked[0].sizeBytes, Buffer.from(png,'base64').length);
  assert.match(checked[0].sha256, /^[a-f0-9]{64}$/);
  for (const dataUrl of ['https://example.com/a.png', 'file:///tmp/a.png', 'data:image/svg+xml;base64,PHN2Zz4=', 'data:image/jpeg;base64,'+png, 'data:image/png;base64,a']) assert.throws(() => validatePromptImages([{...image, dataUrl}]));
  assert.throws(() => validatePromptImages([image, image]), /Invalid image/);
  assert.throws(() => validatePromptImages(Array(5).fill(image)), /up to 4/);
  assert.throws(() => validatePromptImages([{...image, dataUrl:'x'.repeat(7*1024*1024)}]), /5 MB/);
  const bytes=Buffer.from(png,'base64');bytes.writeUInt32BE(9000,16);
  assert.throws(() => validatePromptImages([{...image,dataUrl:'data:image/png;base64,'+bytes.toString('base64')}]), /dimensions/);
  assert.equal(imageContent('Text', [], false), 'Text');
  assert.throws(() => imageContent('Text', checked, false), /text only/);
  assert.deepEqual(imageContent('Text', checked, true), [{type:'text',text:'Text'},{type:'image_url',image_url:{url:image.dataUrl}}]);
});
test('production KimiSession sends multimodal parts, retains exact image bytes in logs, and keeps text-only turns working', async t => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'kimi-images-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.writeFileSync(path.join(root,'config.toml'),'default_model="industrial"\n');
  const prompts=[], events=[];
  const runtime={shareDir:root,apiKey:'test-key',profile:{thinking:false,imageInput:true},revision:0};
  const factory=()=>({close:async()=>{},prompt(content){prompts.push(content);return {result:Promise.resolve({status:'completed'}),async *[Symbol.asyncIterator](){}};}});
  const session=new KimiSession(root,()=>({domain:'test',stage:'test',capabilityIds:[],skills:[],tools:[]}),()=>null,()=>null,event=>events.push(event),()=>runtime,factory,{directory:path.join(root,'logs')});t.after(()=>session.close());
  await session.run('Describe shapes',[image]);
  assert.equal(prompts[0][1].image_url.url,image.dataUrl);
  assert.match(prompts[0][0].text,/user-provided visual references/);
  const rows=fs.readFileSync(events.find(event=>event.type==='diagnostic-log').path,'utf8').trim().split('\n').map(JSON.parse);
  const prompt=rows.find(row=>row.type==='prompt').payload;
  assert.equal(prompt.content[1].image_url.url,image.dataUrl);
  assert.equal(prompt.images[0].width,1);
  await session.run('Follow up');assert.equal(typeof prompts[1],'string');
  runtime.profile.imageInput=false;
  await assert.rejects(session.run('Unsupported',[image]),/Enable Image input/);
  assert.equal(prompts.length,2,'no silent text fallback');
});
